# FROM node:20-alpine

# COPY react_api_backend /doc_mvc

# WORKDIR /doc_mvc

# RUN npm install


# CMD ["node","index.js"]


# Stage 1: Build React application
FROM node:14 as build

# Set the working directory in the container
WORKDIR /backend

# Copy my-react-app to the working directory
COPY react_api_backend ./

# Install dependencies
RUN npm ci

# Copy the source code to the working directory
COPY . .

# Build the React application
# RUN npm run build

# Stage 2: Serve React application using Nginx
# FROM nginx:latest

# Copy the built files from the previous stage to the Nginx public directory
# COPY --from=build /app/build /usr/share/nginx/html

# Expose the default Nginx port
# EXPOSE 80

# Start Nginx when the container launches
CMD ["node","index.js"]