name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: rajeshthapaliya/backend

      - name: Deploy to EC2 instance
        uses: rajeshthapaliya/Docker-using-github-action/backend@main
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
               ssh -i key username@host "docker stop my-container && docker rm my-container"
               ssh -i key username@host "docker pull rajeshthapaliya/backend"
               ssh -i key username@host "docker run -d --name my-container -p 80:80 rajeshthapaliya/backend"
