name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@vl
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rajeshthapaliya/backend:{{ github.sha }}

      - name: Deploy to EC2 instance
        uses: rajeshthapaliya/Docker-using-github-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop backend || true
            docker rm backend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend:{{ github.sha }}
            docker run -d --name backend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/backend:{{ github.sha }}
