name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: rajeshthapaliya/backend
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: rajeshthapaliya/frontend 

      - name: Deploy to EC2 instance
        uses: rajeshthapaliya/Docker-using-github-action/backend@main
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
               ssh -i key username@host "sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend"
               ssh -i key username@host "sudo docker run -d --name my-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/backend"
               
      - name: Deploy to EC2 instance
        uses: rajeshthapaliya/Docker-using-github-action/frontend@main
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
               ssh -i key username@host "sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend"
               ssh -i key username@host "sudo docker run -d --name my-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/frontend"        
