name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: rajeshthapaliya/backend
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: rajeshthapaliya/frontend 
          
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
               sudo docker stop backend || true
               sudo docker rm backend || true
               sudo docker pull rajeshthapaliya/backend:latest
               sudo docker run -d --name backend -p 8080:8080 rajeshthapaliya/backend
    
               sudo docker stop frontend || true
               sudo docker rm frontend || true
               sudo docker pull rajeshthapaliya/frontend:latest
               sudo docker run -d --name frontend -p 80:80 rajeshthapaliya/frontend
